# Generated by Django 4.0.2 on 2022-11-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='University',
        ),
    ]
