# Generated by Django 4.0.2 on 2022-11-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='uneversity',
            new_name='university',
        ),
    ]
