# Generated by Django 4.0.2 on 2022-12-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_alter_student_admission_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
