# Generated by Django 4.0.2 on 2022-12-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_alter_university_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='full_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
